---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version-file: '.python-version'

      - uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: |
            venv
          key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/*requirements.txt') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip pip-tools
          pip-sync requirements.txt dev-requirements.txt

      - name: Run the linter
        run: |
          source venv/bin/activate
          make lint

      - name: Run the tests
        run: |
          cp env.example src/.env
          source venv/bin/activate
          make test

  build-docker-image:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get python version
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version-file: '.python-version'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image identifier
        id: image-identifier
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/${{ steps.image-identifier.outputs.lowercase }}:latest
            ghcr.io/${{ steps.image-identifier.outputs.lowercase }}:${{ github.sha }}
          build-args: |
            PYTHON_VERSION=${{ steps.setup-python.outputs.python-version }}
            RELEASE=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-docker-image
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Read image identifiers
        id: image
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Update backend image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: circle
          key: ${{ secrets.DEPLOY_KEY }}
          script: docker service update tinkoff-diadoc_service --image ghcr.io/${{ steps.image.outputs.lowercase }}:${{ github.sha }} --with-registry-auth
